"""Regression tests against the machine-verified ``cflibs-formal`` spec.

Each test drives this pipeline's **real** physics functions with the verified-spec fixtures
(``tests/data/cflibs_formal_oracle/fixtures.json``, generated by a Lean 4 + mathlib proof and
classified faithful by a whole-corpus literature-validity audit) and asserts they reproduce the
proven values. A refactor that silently breaks a formula/sign/factor is caught here.

The spec is dimensionless (``kB = T = Fcal = 1``, ``E`` in units of ``kB*T``); this pipeline is
physical (Kelvin/eV). The bridge is ``E_eV = E * KB_EV * T_REF`` so
``exp(-E_eV/(KB_EV*T_REF)) = exp(-E)`` reproduces the spec's Boltzmann factor, with constant
wavelength so the energy ordinate ``ln(I*lambda/gA)`` shares the spec's reduced-ordinate slope.
See ``tests/data/cflibs_formal_oracle/README.md``.

Coverage: escape factor, partition function, closure composition, two-line temperature,
error-budget thresholds, Stark width->n_e, and the McWhirter LTE bound are regression-tested
here against the verified spec. Intentionally NOT unit-regressed (no pure function to pin):
the Saha factor is solver/uncertainty-bound in this pipeline (the spec's ``saha-boltzmann``
fixture validates the Saha math; the pipeline's Saha is exercised end-to-end), and the classic
single-line density de-normalisation is solver-intrinsic (covered by the round-trip tests).
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pytest

from cflibs.core.constants import KB_EV
from cflibs.inversion.common.data_structures import LineObservation
from cflibs.inversion.physics import error_budget as eb
from cflibs.inversion.physics.boltzmann import BoltzmannPlotFitter
from cflibs.inversion.physics.closure import ClosureEquation
from cflibs.inversion.physics.line_selection import LineSelector
from cflibs.inversion.physics.self_absorption import _escape_factor
from cflibs.plasma.partition import direct_sum_partition_function

FIXTURES_PATH = (
    Path(__file__).resolve().parents[2] / "data" / "cflibs_formal_oracle" / "fixtures.json"
)
T_REF = 10_000.0  # reference temperature (K) for the dimensionless -> eV mapping
LAMBDA_CONST = 500.0  # constant wavelength (nm): cancels in the slope, so any value works
RTOL = 1e-6  # formula-correctness tolerance; real bugs differ by >> this


@pytest.fixture(scope="module")
def fixtures() -> dict:
    if not FIXTURES_PATH.exists():
        pytest.skip(f"verified-spec fixtures not found at {FIXTURES_PATH}")
    return json.loads(FIXTURES_PATH.read_text())


def _scenario(fixtures: dict, kind: str) -> dict:
    return next(s for s in fixtures["scenarios"] if s["kind"] == kind)


def _to_ev(e_dimensionless: float) -> float:
    """Map a dimensionless spec energy to eV at the reference temperature."""
    return e_dimensionless * KB_EV * T_REF


@pytest.mark.unit
def test_self_absorption_escape_factor_matches_spec(fixtures: dict) -> None:
    """``_escape_factor(tau)`` reproduces the verified ``SA(tau) = (1-e^-tau)/tau``.

    Pins ``SelfAbsorption.selfAbsorptionFactor`` (audited: faithful curve-of-growth escape
    factor).
    """
    els = _scenario(fixtures, "multi-element-composition")["elements"]
    taus = [e["tau"] for e in els]
    assert any(t > 0 for t in taus), "fixture must exercise optically-thick lines"
    for tau in taus:
        expected = (1.0 - math.exp(-tau)) / tau
        assert _escape_factor(tau) == pytest.approx(expected, rel=RTOL)


@pytest.mark.unit
def test_partition_function_matches_spec(fixtures: dict) -> None:
    """``direct_sum_partition_function`` reproduces the verified ``U = sum_k g_k e^-E_k``.

    Pins ``Boltzmann.partitionFunction``. Uses a huge ionization potential so no level is cut.
    """
    els = _scenario(fixtures, "multi-element-composition")["elements"]
    for el in els:
        g = np.asarray(el["g"], dtype=float)
        e_ev = np.asarray([_to_ev(e) for e in el["E"]], dtype=float)
        u = direct_sum_partition_function(T_REF, g, e_ev, ip_ev=1.0e9)
        assert u == pytest.approx(el["partitionFunction"], rel=RTOL)


@pytest.mark.unit
def test_closure_composition_matches_spec(fixtures: dict) -> None:
    """``ClosureEquation.apply_standard`` reproduces the verified composition ``C_s = N_s/sum N``.

    Feeds the Boltzmann-plot intercepts ``q_s = ln(N_s/U_s)`` (Fcal=1) and partition functions;
    closure must return the true mole fractions and sum to 1. Pins
    ``Closure.composition_sum_one`` / ``classic_sound``.
    """
    sc = _scenario(fixtures, "multi-element-composition")
    els = sc["elements"]
    intercepts = {e["sym"]: math.log(e["N"] / e["partitionFunction"]) for e in els}
    partition_funcs = {e["sym"]: e["partitionFunction"] for e in els}

    result = ClosureEquation.apply_standard(intercepts, partition_funcs)
    conc = result.concentrations

    assert sum(conc.values()) == pytest.approx(1.0, rel=RTOL)
    for i, el in enumerate(els):
        assert conc[el["sym"]] == pytest.approx(sc["true_composition"][i], rel=RTOL)


@pytest.mark.unit
def test_boltzmann_two_line_temperature_matches_spec(fixtures: dict) -> None:
    """``BoltzmannPlotFitter.fit`` recovers ``T_REF`` from the verified forward intensities.

    Builds ``LineObservation``s from one element's forward spectrum (constant wavelength) and
    checks the slope-recovered temperature equals the reference. Pins
    ``Classic.classic_temperature_correct`` (two-line Boltzmann slope).
    """
    els = _scenario(fixtures, "multi-element-composition")["elements"]
    el = els[0]
    observations = [
        LineObservation(
            wavelength_nm=LAMBDA_CONST,
            intensity=el["intensities"][k],
            intensity_uncertainty=el["intensities"][k] * 1e-6,
            element=el["sym"],
            ionization_stage=0,
            E_k_ev=_to_ev(el["E"][k]),
            g_k=int(el["g"][k]),
            A_ki=el["A"][k],
        )
        for k in range(len(el["g"]))
    ]

    result = BoltzmannPlotFitter().fit(observations)
    assert result.temperature_K == pytest.approx(T_REF, rel=1e-4)


@pytest.mark.unit
def test_error_budget_core_matches_spec(fixtures: dict) -> None:
    """The ``error_budget`` dimensionless core reproduces the verified ``error-budget`` fixture.

    Pins the threshold formulas and their tightness invariants:
    ``requiredEnergySpread_sufficient`` / ``maxPerLineError_sufficient`` /
    ``olsSlope_noise_gain`` / ``temp_rel_error_eq`` / ``composition_target_sufficient``.
    """
    sc = _scenario(fixtures, "error-budget")
    i, th = sc["inputs"], sc["thresholds"]

    assert eb.required_energy_spread(i["tauBeta"], i["snr"], i["n"]) == pytest.approx(
        th["requiredEnergySpread"], rel=RTOL
    )
    assert eb.max_per_line_error(i["tauBeta"], i["n"], i["ssE"]) == pytest.approx(
        th["maxPerLineError"], rel=RTOL
    )
    assert eb.required_min_lines_stat(i["tauBeta"], i["snr"], i["vPerLine"]) == pytest.approx(
        th["requiredMinLinesStat"], rel=RTOL
    )
    assert eb.slope_target_from_temp_rel(i["relTtarget"], i["kB"] * i["T"]) == pytest.approx(
        th["slopeTargetFromTempRel"], rel=RTOL
    )
    assert eb.density_budget_from_composition(i["tauC"], i["Shat"], i["card"]) == pytest.approx(
        th["densityBudgetFromComposition"], rel=RTOL
    )

    # Tightness: at the derived threshold the bound exactly equals the target.
    req_ss = eb.required_energy_spread(i["tauBeta"], i["snr"], i["n"])
    assert eb.slope_error_bound(i["snr"], i["n"], req_ss) == pytest.approx(i["tauBeta"], rel=RTOL)
    max_eps = eb.max_per_line_error(i["tauBeta"], i["n"], i["ssE"])
    assert eb.slope_error_bound(max_eps, i["n"], i["ssE"]) == pytest.approx(i["tauBeta"], rel=RTOL)


@pytest.mark.unit
def test_error_budget_physical_layer_roundtrips() -> None:
    """The eV/Kelvin adoption layer is self-consistent (span <-> SNR <-> rel-T error)."""
    target, snr, n, t_k = 0.05, 12.0, 6, T_REF

    span = eb.required_energy_span_ev(target, snr, n, t_k)
    ss_e = n * (1.0 / 12.0) * span**2  # uniform model used by required_energy_span_ev
    assert eb.temp_rel_error_bound(1.0 / snr, n, ss_e, t_k) == pytest.approx(target, rel=RTOL)

    # Min SNR at exactly that span reproduces the assumed SNR (inverse of the spread inversion).
    assert eb.min_snr_for_target(target, span, n, t_k) == pytest.approx(snr, rel=RTOL)


@pytest.mark.unit
def test_line_selector_from_accuracy_target_is_spec_derived() -> None:
    """``LineSelector.from_accuracy_target`` derives gates from a target accuracy (not tuned).

    Existing ``__init__`` defaults are untouched; the derived constructor wires the verified
    thresholds into ``min_energy_spread_ev`` / ``min_snr`` / ``min_lines_per_element``.
    """
    target, n, t_k, snr = 0.05, 6, T_REF, 12.0
    sel = LineSelector.from_accuracy_target(target, n_lines=n, temperature_K=t_k, snr=snr)

    assert sel.min_snr == snr
    assert sel.min_lines_per_element == n
    assert sel.min_energy_spread_ev == pytest.approx(
        eb.required_energy_span_ev(target, snr, n, t_k), rel=RTOL
    )
    assert sel.min_energy_spread_ev > 0

    # The tuned default constructor is unchanged.
    assert LineSelector().min_energy_spread_ev == 2.0
    assert LineSelector().min_snr == 10.0


@pytest.mark.unit
def test_stark_density_matches_spec(fixtures: dict) -> None:
    """``estimate_ne_from_stark`` reproduces the verified Griem linear inverse ``nRef*width/(2w)``.

    The spec is dimensionless; the pipeline's ``REF_NE`` enters via ``stark_w_ref = 2w`` at the
    reference temperature (so the ``(T/ref_T_K)^alpha`` correction is unity). Pins
    ``StarkBroadening.starkDensity_recovers``.
    """
    from cflibs.radiation.stark import REF_NE, REF_T_K, estimate_ne_from_stark

    c = _scenario(fixtures, "stark")["constants"]
    w, n_ref, width = c["w"], c["nRef"], c["width"]
    ne_oracle = _scenario(fixtures, "stark")["checks"]["stark_density"]["ne"]

    ne_pipeline = estimate_ne_from_stark(width, REF_T_K, stark_w_ref=2.0 * w)
    assert ne_pipeline == pytest.approx(REF_NE * ne_oracle / n_ref, rel=RTOL)


@pytest.mark.unit
def test_mcwhirter_bound_matches_spec(fixtures: dict) -> None:
    """The pipeline's McWhirter floor reproduces the verified ``1.6e12 * sqrt(T) * dE^3``.

    Pins ``StarkBroadening.mcWhirterBound``: the verified constant and the bound shape.
    """
    from cflibs.core.constants import MCWHIRTER_CONST
    from cflibs.plasma.lte_validator import LTEValidator

    ch = _scenario(fixtures, "stark")["checks"]["mcwhirter"]
    c = _scenario(fixtures, "stark")["constants"]
    t_mc, de, shape = c["T"], c["dE"], ch["shape"]

    assert MCWHIRTER_CONST == pytest.approx(1.6e12, rel=RTOL)
    required = LTEValidator.check_mcwhirter(t_mc, 1.0e17, de).n_e_required
    assert required == pytest.approx(MCWHIRTER_CONST * shape, rel=RTOL)
