"""
Inversion algorithms for CF-LIBS.

This package exposes the public inversion API without importing optional or
plotting-heavy stacks at module import time. Symbols are loaded lazily when
accessed, which keeps beginner CLI workflows quiet and fast.
"""

from __future__ import annotations

from importlib import import_module
from importlib.util import find_spec


def _has_modules(*module_names: str) -> bool:
    """Return whether all optional modules are importable without importing them."""
    return all(find_spec(module_name) is not None for module_name in module_names)


HAS_HYBRID = _has_modules("jax")
HAS_JOINT_OPTIMIZER = _has_modules("jax")
HAS_PCA_JAX = _has_modules("jax")
HAS_BAYESIAN = _has_modules("jax", "numpyro")
HAS_NESTED = _has_modules("dynesty")
HAS_UNCERTAINTIES = _has_modules("uncertainties")

_ATTRIBUTE_EXPORT_GROUPS = {
    "cflibs.inversion.common.data_structures": [
        "LineObservation",
        "BoltzmannFitResult",
        "FitMethod",
    ],
    "cflibs.inversion.physics.boltzmann": ["BoltzmannPlotFitter"],
    "cflibs.inversion.physics.closure": [
        "ClosureEquation",
        "ClosureResult",
        "ClosureMode",
        "clr_transform",
        "ilr_transform",
        "ilr_inverse",
    ],
    "cflibs.inversion.solve.iterative": ["IterativeCFLIBSSolver", "CFLIBSResult"],
    "cflibs.inversion.solve.closed_form": ["ClosedFormILRSolver", "ClosedFormConfig"],
    "cflibs.inversion.physics.quality": [
        "QualityMetrics",
        "QualityAssessor",
        "compute_reconstruction_chi_squared",
    ],
    "cflibs.inversion.physics.line_selection": [
        "LineScore",
        "LineSelectionResult",
        "LineSelector",
        "identify_resonance_lines",
    ],
    "cflibs.inversion.identify.line_detection": [
        "LineDetectionResult",
        "detect_line_observations",
    ],
    "cflibs.inversion.common.element_id": [
        "IdentifiedLine",
        "ElementIdentification",
        "ElementIdentificationResult",
        "to_line_observations",
    ],
    "cflibs.inversion.identify.correlation": ["CorrelationIdentifier"],
    "cflibs.inversion.identify.alias": ["ALIASIdentifier"],
    "cflibs.inversion.identify.comb": ["CombIdentifier"],
    "cflibs.inversion.preprocess.preprocessing": [
        "estimate_baseline",
        "estimate_baseline_snip",
        "estimate_baseline_als",
        "estimate_noise",
        "detect_peaks",
        "detect_peaks_auto",
        "robust_normalize",
        "BaselineMethod",
    ],
    "cflibs.inversion.preprocess.deconvolution": [
        "VoigtFitResult",
        "DeconvolutionResult",
        "deconvolve_peaks",
        "group_peaks",
    ],
    "cflibs.inversion.physics.self_absorption": [
        "AbsorptionCorrectionResult",
        "SelfAbsorptionResult",
        "SelfAbsorptionCorrector",
        "estimate_optical_depth_from_intensity_ratio",
    ],
    "cflibs.inversion.physics.cdsb": [
        "CDSBPlotter",
        "CDSBResult",
        "CDSBLineObservation",
        "CDSBConvergenceStatus",
        "LineOpticalDepth",
        "create_cdsb_observation",
        "from_transition",
    ],
    "cflibs.inversion.physics.uncertainty": [
        "MonteCarloUQ",
        "MonteCarloResult",
        "PerturbationType",
        "AtomicDataUncertainty",
        "run_monte_carlo_uq",
        "HAS_JOBLIB",
        "create_boltzmann_uncertainties",
        "temperature_from_slope",
        "saha_factor_with_uncertainty",
        "propagate_through_closure_standard",
        "propagate_through_closure_matrix",
        "extract_values_and_uncertainties",
    ],
    "cflibs.inversion.preprocess.outliers": [
        "OutlierMethod",
        "SAMResult",
        "SpectralAngleMapper",
        "sam_distance",
        "detect_outlier_spectra",
        "MADResult",
        "MADOutlierDetector",
        "mad_outliers_1d",
        "mad_outliers_spectra",
        "mad_clean_channels",
    ],
    "cflibs.inversion.physics.matrix_effects": [
        "MatrixType",
        "MatrixClassificationResult",
        "CorrectionFactor",
        "CorrectionFactorDB",
        "MatrixCorrectionResult",
        "MatrixEffectCorrector",
        "InternalStandardResult",
        "InternalStandardizer",
        "combine_corrections",
    ],
    "cflibs.inversion.common.pca": [
        "PCAResult",
        "PCAPipeline",
        "fit_pca",
        "denoise_spectra",
        "explained_variance_curve",
        "pca_transform_jax",
        "pca_inverse_transform_jax",
        "pca_reconstruction_error_jax",
    ],
    "cflibs.inversion.runtime.temporal": [
        "PlasmaPhase",
        "TemporalGateConfig",
        "TimeResolvedSpectrum",
        "PlasmaEvolutionPoint",
        "PlasmaEvolutionProfile",
        "GateOptimizationResult",
        "TemporalSelfAbsorptionResult",
        "TimeResolvedCFLIBSResult",
        "PlasmaEvolutionModel",
        "GateTimingOptimizer",
        "TemporalSelfAbsorptionCorrector",
        "TimeResolvedCFLIBSSolver",
        "create_default_evolution_model",
        "recommend_gate_timing",
    ],
    "cflibs.inversion.runtime.streaming": [
        "AnalysisMode",
        "StreamingConfig",
        "SpectrumPacket",
        "StreamingResult",
        "LatencyStats",
        "SpectrumBuffer",
        "LatencyMonitor",
        "BaseStreamingAnalyzer",
        "FastAnalyzer",
        "StandardAnalyzer",
        "StreamingAnalyzer",
        "EdgeOptimizedModel",
        "create_streaming_pipeline",
    ],
    "cflibs.inversion.solve.coarse_to_fine": [
        "HybridInverter",
        "HybridInversionResult",
        "SpectralFitter",
    ],
    "cflibs.inversion.solve.joint_optimizer": [
        "JointOptimizer",
        "JointOptimizationResult",
        "MultiStartJointOptimizer",
        "LossType",
        "ConvergenceStatus",
        "create_simple_forward_model",
    ],
    "cflibs.inversion.solve.bayesian": [
        "BayesianForwardModel",
        "AtomicDataArrays",
        "NoiseParameters",
        "PriorConfig",
        "MCMCResult",
        "MCMCSampler",
        "log_likelihood",
        "bayesian_model",
        "run_mcmc",
        "create_temperature_prior",
        "create_density_prior",
        "create_concentration_prior",
        "TwoZoneBayesianForwardModel",
        "TwoZonePriorConfig",
        "TwoZoneMCMCSampler",
        "TwoZoneMCMCResult",
        "two_zone_bayesian_model",
        "NestedSampler",
        "NestedSamplingResult",
    ],
}

_ALIASED_EXPORTS = {
    "JointLossType": ("cflibs.inversion.solve.joint_optimizer", "LossType"),
    "JointConvergenceStatus": ("cflibs.inversion.solve.joint_optimizer", "ConvergenceStatus"),
    "ConvergenceStatus": ("cflibs.inversion.solve.bayesian", "ConvergenceStatus"),
}

_MODULE_EXPORTS = {
    attr_name: (module_name, attr_name)
    for module_name, attr_names in _ATTRIBUTE_EXPORT_GROUPS.items()
    for attr_name in attr_names
}
_MODULE_EXPORTS.update(_ALIASED_EXPORTS)

__all__ = [
    "LineObservation",
    "BoltzmannFitResult",
    "BoltzmannPlotFitter",
    "FitMethod",
    "ClosureEquation",
    "ClosureResult",
    "ClosureMode",
    "clr_transform",
    "ilr_transform",
    "ilr_inverse",
    "IterativeCFLIBSSolver",
    "CFLIBSResult",
    "ClosedFormILRSolver",
    "ClosedFormConfig",
    "QualityMetrics",
    "QualityAssessor",
    "compute_reconstruction_chi_squared",
    "LineScore",
    "LineSelectionResult",
    "LineSelector",
    "identify_resonance_lines",
    "LineDetectionResult",
    "detect_line_observations",
    "IdentifiedLine",
    "ElementIdentification",
    "ElementIdentificationResult",
    "to_line_observations",
    "CorrelationIdentifier",
    "ALIASIdentifier",
    "CombIdentifier",
    "estimate_baseline",
    "estimate_baseline_snip",
    "estimate_baseline_als",
    "estimate_noise",
    "detect_peaks",
    "detect_peaks_auto",
    "robust_normalize",
    "BaselineMethod",
    "VoigtFitResult",
    "DeconvolutionResult",
    "deconvolve_peaks",
    "group_peaks",
    "AbsorptionCorrectionResult",
    "SelfAbsorptionResult",
    "SelfAbsorptionCorrector",
    "estimate_optical_depth_from_intensity_ratio",
    "CDSBPlotter",
    "CDSBResult",
    "CDSBLineObservation",
    "CDSBConvergenceStatus",
    "LineOpticalDepth",
    "create_cdsb_observation",
    "from_transition",
    "MonteCarloUQ",
    "MonteCarloResult",
    "PerturbationType",
    "AtomicDataUncertainty",
    "run_monte_carlo_uq",
    "HAS_JOBLIB",
    "OutlierMethod",
    "SAMResult",
    "SpectralAngleMapper",
    "sam_distance",
    "detect_outlier_spectra",
    "MADResult",
    "MADOutlierDetector",
    "mad_outliers_1d",
    "mad_outliers_spectra",
    "mad_clean_channels",
    "MatrixType",
    "MatrixClassificationResult",
    "CorrectionFactor",
    "CorrectionFactorDB",
    "MatrixCorrectionResult",
    "MatrixEffectCorrector",
    "InternalStandardResult",
    "InternalStandardizer",
    "combine_corrections",
    "PCAResult",
    "PCAPipeline",
    "fit_pca",
    "denoise_spectra",
    "explained_variance_curve",
    "PlasmaPhase",
    "TemporalGateConfig",
    "TimeResolvedSpectrum",
    "PlasmaEvolutionPoint",
    "PlasmaEvolutionProfile",
    "GateOptimizationResult",
    "TemporalSelfAbsorptionResult",
    "TimeResolvedCFLIBSResult",
    "PlasmaEvolutionModel",
    "GateTimingOptimizer",
    "TemporalSelfAbsorptionCorrector",
    "TimeResolvedCFLIBSSolver",
    "create_default_evolution_model",
    "recommend_gate_timing",
    "AnalysisMode",
    "StreamingConfig",
    "SpectrumPacket",
    "StreamingResult",
    "LatencyStats",
    "SpectrumBuffer",
    "LatencyMonitor",
    "BaseStreamingAnalyzer",
    "FastAnalyzer",
    "StandardAnalyzer",
    "StreamingAnalyzer",
    "EdgeOptimizedModel",
    "create_streaming_pipeline",
    "HybridInverter",
    "HybridInversionResult",
    "SpectralFitter",
    "JointOptimizer",
    "JointOptimizationResult",
    "MultiStartJointOptimizer",
    "JointLossType",
    "JointConvergenceStatus",
    "create_simple_forward_model",
    "BayesianForwardModel",
    "AtomicDataArrays",
    "NoiseParameters",
    "PriorConfig",
    "MCMCResult",
    "MCMCSampler",
    "ConvergenceStatus",
    "log_likelihood",
    "bayesian_model",
    "run_mcmc",
    "create_temperature_prior",
    "create_density_prior",
    "create_concentration_prior",
    "TwoZoneBayesianForwardModel",
    "TwoZonePriorConfig",
    "TwoZoneMCMCSampler",
    "TwoZoneMCMCResult",
    "two_zone_bayesian_model",
    "NestedSampler",
    "NestedSamplingResult",
    "create_boltzmann_uncertainties",
    "temperature_from_slope",
    "saha_factor_with_uncertainty",
    "propagate_through_closure_standard",
    "propagate_through_closure_matrix",
    "extract_values_and_uncertainties",
    "pca_transform_jax",
    "pca_inverse_transform_jax",
    "pca_reconstruction_error_jax",
    "HAS_HYBRID",
    "HAS_JOINT_OPTIMIZER",
    "HAS_BAYESIAN",
    "HAS_NESTED",
    "HAS_UNCERTAINTIES",
    "HAS_PCA_JAX",
]


def __getattr__(name: str):
    """Lazy-load public inversion exports on first access."""
    if name in _MODULE_EXPORTS:
        module_name, attr_name = _MODULE_EXPORTS[name]
        module = import_module(module_name)
        value = getattr(module, attr_name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
