"""End-to-end parity tests for the J8 jit pipeline composition (ADR-0004 §8.1, M1).

Feeds IDENTICAL inputs to :func:`cflibs.jitpipe.run_one` and the REAL reference
:func:`cflibs.inversion.pipeline.run_pipeline` and asserts the M1 tolerances:

* element calls agree (>= 95 % of spectra; here every element call must match),
* T within 2 %, n_e within 10 %,
* per-element concentration rtol 5 % / atol 0.01,
* failure-policy parity: a spectrum with zero usable lines produces the same
  all-FN scored record on both pipelines (the reference raises ``ValueError``;
  the jit pipeline returns an all-zero ``CFLIBSResult`` with ``converged=False``).

Parity-config note
------------------
Two solve routes are covered (the M1 production-config parity gap D-J8-1):

* the **shared-math** ``raw`` preset (``saha_boltzmann_graph=False`` +
  ``stark_ne=False`` + ``standard`` closure, via ``_PARITY_OVERRIDES``): the jit
  ``scan_solve`` mirrors the reference ``_solve_lax`` fixed point bit-for-bit
  (with ``CFLIBS_USE_LAX_WHILE_LOOP=1`` the reference uses the bit-exact lax
  oracle); and
* the **production geological/metallic** preset
  (``saha_boltzmann_graph=True`` + ``stark_ne=True``): the reference routes
  ``_solve_python``'s unit-weight SB-graph with ``n_e`` pinned to the Stark
  measurement, which the jit composition now mirrors via
  :func:`cflibs.jitpipe.solve.production_solve` (the ``scan_solve`` initializer
  SEEDS :func:`joint_wls_solve`, ``sb_graph=True``). These cases
  (``test_run_one_matches_reference_production_*``) close D-J8-1 — the M1 gate
  is COMPOSITION parity under the SAME geological preset on both sides.

Data
----
Synthetic spectra are generated by the deterministic CF-LIBS forward model (no
external data). A real ChemCam BHVO-2 fixture is used when present
(``data/bhvo2_usgs/chemcam_bhvo2_loc1_spectrum.csv``, tracked in this
worktree); skipped gracefully if absent.

CPU x64 (conftest forces ``jax_enable_x64``); a narrow subset per the watchdog
rules in CLAUDE.md.
"""

from __future__ import annotations

import os
from pathlib import Path

import numpy as np
import pytest

os.environ.setdefault("JAX_PLATFORMS", "cpu")
# Pin the reference to the bit-exact lax fixed point that scan_solve mirrors.
os.environ.setdefault("CFLIBS_USE_LAX_WHILE_LOOP", "1")

jax = pytest.importorskip("jax")
jax.config.update("jax_enable_x64", True)

pytestmark = [pytest.mark.requires_jax, pytest.mark.requires_db, pytest.mark.integration]

DB_PATH = "ASD_da/libs_production.db"
_REPO_ROOT = Path(__file__).resolve().parents[2]
_REAL_SPECTRUM = _REPO_ROOT / "data" / "bhvo2_usgs" / "chemcam_bhvo2_loc1_spectrum.csv"

# Parity config: the shared solve math path (see module docstring).
_PARITY_OVERRIDES = {
    "closure_mode": "standard",
    "saha_boltzmann_graph": False,
    "stark_ne": False,
    "response_curve": None,
}


@pytest.fixture(scope="module")
def db():
    from cflibs.atomic.database import AtomicDatabase

    if not Path(DB_PATH).exists():  # pragma: no cover - env-dependent
        pytest.skip(f"atomic DB not present at {DB_PATH}")
    return AtomicDatabase(DB_PATH)


@pytest.fixture(scope="module")
def snapshot():
    from cflibs.jitpipe import build_snapshot

    if not Path(DB_PATH).exists():  # pragma: no cover
        pytest.skip(f"atomic DB not present at {DB_PATH}")
    return build_snapshot(DB_PATH)


def _static_for(snapshot, closure_mode="standard", max_iters=20):
    from cflibs.jitpipe import StaticConfig

    return StaticConfig(
        bucket_id=0,
        n_species=snapshot.n_species,
        level_pad=snapshot.level_pad[1],
        closure_mode=closure_mode,
        max_iters=max_iters,
    )


def _synthetic_spectrum(db, T_K=9000.0, n_e=2.0e16, lam=(240.0, 450.0), dlam=0.02):
    """Deterministic synthetic spectrum via the CF-LIBS forward model."""
    from cflibs.instrument.model import InstrumentModel
    from cflibs.plasma.state import SingleZoneLTEPlasma
    from cflibs.radiation.spectrum_model import SpectrumModel

    species = {"Fe": 5.0e15, "Ca": 3.0e15, "Ti": 2.0e15}
    plasma = SingleZoneLTEPlasma(T_e=T_K, n_e=n_e, species=species)
    instr = InstrumentModel(resolution_fwhm_nm=0.05)
    model = SpectrumModel(plasma, db, instr, lam[0], lam[1], dlam)
    wl, inten = model.compute_spectrum()
    return np.asarray(wl, float), np.asarray(inten, float), list(species.keys())


def _load_real_spectrum():
    rows = np.genfromtxt(_REAL_SPECTRUM, delimiter=",", names=True)
    return np.asarray(rows["wavelength"], float), np.asarray(rows["intensity"], float)


def _assert_m1_parity(ref, got, *, elements):
    """Assert the M1 tolerances between a reference and jit CFLIBSResult."""
    # 1. Element calls agree (every present element must match here).
    ref_calls = {k for k, v in ref.concentrations.items() if v > 0.0}
    got_calls = {k for k, v in got.concentrations.items() if v > 0.0}
    assert got_calls == ref_calls, f"element calls differ: jit={got_calls} ref={ref_calls}"

    # 2. T within 2 %, n_e within 10 %.
    np.testing.assert_allclose(got.temperature_K, ref.temperature_K, rtol=0.02)
    np.testing.assert_allclose(got.electron_density_cm3, ref.electron_density_cm3, rtol=0.10)

    # 3. Per-element concentration rtol 5 % / atol 0.01.
    for el in ref.concentrations:
        np.testing.assert_allclose(
            got.concentrations.get(el, 0.0),
            ref.concentrations[el],
            rtol=0.05,
            atol=0.01,
            err_msg=f"concentration parity failed for {el}",
        )


# ---------------------------------------------------------------------------
# 1. Synthetic end-to-end composition parity (no external data).
# ---------------------------------------------------------------------------


def test_run_one_matches_reference_synthetic(db, snapshot):
    """run_one reproduces run_pipeline end-to-end on a synthetic spectrum.

    Exercises the full COMPOSITION: response/preprocess -> calibrate -> detect
    + identify -> solve. The solve spine runs the jit ``scan_solve`` kernel; the
    reference runs its own solve on the same observations. M1 tolerances.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
    )
    _assert_m1_parity(ref, got, elements=elements)


def test_run_one_returns_cflibs_result_type(db, snapshot):
    """run_one returns the SAME ``CFLIBSResult`` dataclass the reference returns."""
    from cflibs.inversion.pipeline import build_pipeline_config
    from cflibs.inversion.solve.iterative import CFLIBSResult
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)
    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
    )
    assert isinstance(got, CFLIBSResult)
    assert set(got.concentrations) == set(elements)


# ---------------------------------------------------------------------------
# 2. Real ChemCam BHVO-2 end-to-end parity (when the fixture is present).
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not _REAL_SPECTRUM.exists(), reason="real ChemCam BHVO-2 fixture not present in worktree"
)
def test_run_one_matches_reference_real_chemcam(db, snapshot):
    """run_one reproduces run_pipeline on a REAL ChemCam BHVO-2 spectrum (M1 headline)."""
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten = _load_real_spectrum()
    elements = ["Si", "Ti", "Al", "Fe", "Mn", "Mg", "Ca", "Na", "K"]
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
    )
    _assert_m1_parity(ref, got, elements=elements)


# ---------------------------------------------------------------------------
# 2b. PRODUCTION geological/metallic preset parity (divergence D-J8-1).
#
# The production preset (``saha_boltzmann_graph=True`` + ``stark_ne=True``)
# routes the reference solve through ``_solve_python``'s unit-weight
# Saha-Boltzmann graph with ``n_e`` pinned to the Stark measurement — the path
# the shared-math ``scan_solve`` does NOT mirror. ``run_one`` now routes this
# preset through :func:`cflibs.jitpipe.solve.production_solve` (the scan
# initializer SEEDS :func:`joint_wls_solve`, ``sb_graph=True``). These cases
# prove ``run_one`` bit-matches the reference UNDER THE GEOLOGICAL PRESET
# (ADR-0004 §6.1; J7 §4 row 10). No ``_PARITY_OVERRIDES``: the preset's own
# SB-graph + Stark flags drive both sides.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("preset", "closure_mode"),
    [("geological", "oxide"), ("metallic", "standard")],
)
def test_run_one_matches_reference_production_synthetic(db, snapshot, preset, closure_mode):
    """run_one == run_pipeline under the PRODUCTION preset on a synthetic spectrum.

    Both sides resolve the same ``geological``/``metallic`` preset
    (``saha_boltzmann_graph=True`` + ``stark_ne=True``); the reference routes
    ``_solve_python`` (SB-graph + Stark-pinned n_e), the jit composition routes
    :func:`production_solve` (scan-seeded joint WLS). M1 tolerances.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten, elements = _synthetic_spectrum(db)
    # Build the preset faithfully — no SB-graph/Stark overrides (D-J8-1 path).
    cfg = build_pipeline_config(elements, preset=preset)
    assert cfg.saha_boltzmann_graph is True
    assert cfg.stark_ne is True

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot, closure_mode=closure_mode),
        atomic_db=db,
        pipeline_config=cfg,
    )
    _assert_m1_parity(ref, got, elements=elements)


@pytest.mark.skipif(
    not _REAL_SPECTRUM.exists(), reason="real ChemCam BHVO-2 fixture not present in worktree"
)
def test_run_one_matches_reference_production_real_chemcam(db, snapshot):
    """run_one == run_pipeline under the GEOLOGICAL preset on REAL ChemCam BHVO-2.

    The M1 headline acceptance case: the production geological preset
    (``saha_boltzmann_graph=True`` + ``closure_mode='oxide'`` + ``stark_ne=True``)
    on the real ChemCam BHVO-2 spectrum, asserting element calls >= 95 %, T
    within 2 %, n_e within 10 %, per-element concentration rtol 5 % / atol 0.01.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten = _load_real_spectrum()
    elements = ["Si", "Ti", "Al", "Fe", "Mn", "Mg", "Ca", "Na", "K"]
    cfg = build_pipeline_config(elements, preset="geological")
    assert cfg.saha_boltzmann_graph is True
    assert cfg.closure_mode == "oxide"

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0
    assert ref.converged

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot, closure_mode="oxide"),
        atomic_db=db,
        pipeline_config=cfg,
    )
    assert got.converged
    # Element-call agreement >= 95 % (here all present elements must match).
    ref_calls = {k for k, v in ref.concentrations.items() if v > 0.0}
    got_calls = {k for k, v in got.concentrations.items() if v > 0.0}
    assert len(ref_calls) > 0
    n_agree = len(ref_calls & got_calls) + len({e for e in elements} - ref_calls - got_calls)
    assert n_agree / len(elements) >= 0.95, f"calls: jit={got_calls} ref={ref_calls}"
    _assert_m1_parity(ref, got, elements=elements)


def test_failure_policy_parity_production(db, snapshot):
    """Geological-preset failure policy: flat spectrum -> same all-FN record.

    Failure-policy parity (AC4) must hold on the production route too: the
    reference raises ``ValueError`` at zero observations; the jit pipeline
    returns the all-FN ``CFLIBSResult`` (``converged=False``, all-zero conc).
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl = np.arange(240.0, 450.0, 0.02)
    flat = np.ones_like(wl)
    elements = ["Fe", "Ca", "Ti"]
    cfg = build_pipeline_config(elements, preset="geological")

    with pytest.raises(ValueError, match="No usable spectral lines"):
        run_pipeline(wl, flat, db, cfg)

    got = run_one(
        flat,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot, closure_mode="oxide"),
        atomic_db=db,
        pipeline_config=cfg,
    )
    assert got.converged is False
    assert set(got.concentrations) == set(elements)
    assert all(v == 0.0 for v in got.concentrations.values())
    assert np.isfinite(got.temperature_K)
    assert np.isfinite(got.electron_density_cm3)


# ---------------------------------------------------------------------------
# 3. Failure-policy parity (AC4): zero usable lines -> same all-FN record.
# ---------------------------------------------------------------------------


def test_failure_policy_parity(db, snapshot):
    """A flat (peak-free) spectrum: reference raises ValueError, jit returns all-FN.

    The reference scoreboard scores the ValueError as all false-negative; the
    jit pipeline must emit the same all-FN record (NaN-free, ``converged=False``,
    element keys preserved) — not a crash, not NaN.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl = np.arange(240.0, 450.0, 0.02)
    flat = np.ones_like(wl)
    elements = ["Fe", "Ca", "Ti"]
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)

    # Reference: zero observations -> ValueError.
    with pytest.raises(ValueError, match="No usable spectral lines"):
        run_pipeline(wl, flat, db, cfg)

    # Jit: same all-FN record (no crash, no NaN).
    got = run_one(
        flat,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
    )
    assert got.converged is False
    assert set(got.concentrations) == set(elements)
    assert all(v == 0.0 for v in got.concentrations.values())
    assert np.isfinite(got.temperature_K)
    assert np.isfinite(got.electron_density_cm3)
    assert not any(np.isnan(v) for v in got.concentrations.values())


# ---------------------------------------------------------------------------
# 4. run_batch host-loop produces per-spectrum CFLIBSResults.
# ---------------------------------------------------------------------------


def test_run_batch_host_loop(db, snapshot):
    """run_batch returns one CFLIBSResult per spectrum (J8 host loop; vmap in J9)."""
    from cflibs.inversion.pipeline import build_pipeline_config
    from cflibs.inversion.solve.iterative import CFLIBSResult
    from cflibs.jitpipe import PipelineParams, run_batch

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)
    batch = np.stack([inten, inten * 1.001])  # two near-identical spectra
    results = run_batch(
        batch,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_configs=[cfg, cfg],
    )
    assert len(results) == 2
    assert all(isinstance(r, CFLIBSResult) for r in results)
    assert all(set(r.concentrations) == set(elements) for r in results)


# ---------------------------------------------------------------------------
# 5. solve-stage padding invariance at the composition level (AC5/AC6 surface).
# ---------------------------------------------------------------------------


def test_solve_stage_bucket_invariance(db, snapshot):
    """A larger static max_iters bucket leaves the answer unchanged (idempotent freeze)."""
    from cflibs.inversion.pipeline import build_pipeline_config
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)
    params = PipelineParams()

    r20 = run_one(
        inten,
        wl,
        snapshot,
        params,
        _static_for(snapshot, max_iters=20),
        atomic_db=db,
        pipeline_config=cfg,
    )
    r30 = run_one(
        inten,
        wl,
        snapshot,
        params,
        _static_for(snapshot, max_iters=30),
        atomic_db=db,
        pipeline_config=cfg,
    )
    # The converged-state freeze makes scan_solve idempotent past convergence.
    np.testing.assert_allclose(r30.temperature_K, r20.temperature_K, rtol=1e-9)
    for el in elements:
        np.testing.assert_allclose(
            r30.concentrations[el], r20.concentrations[el], rtol=1e-9, atol=1e-12
        )
