"""End-to-end parity tests for the J8 jit pipeline composition (ADR-0004 §8.1, M1).

Feeds IDENTICAL inputs to :func:`cflibs.jitpipe.run_one` and the REAL reference
:func:`cflibs.inversion.pipeline.run_pipeline` and asserts the M1 tolerances:

* element calls agree (>= 95 % of spectra; here every element call must match),
* T within 2 %, n_e within 10 %,
* per-element concentration rtol 5 % / atol 0.01,
* failure-policy parity: a spectrum with zero usable lines produces the same
  all-FN scored record on both pipelines (the reference raises ``ValueError``;
  the jit pipeline returns an all-zero ``CFLIBSResult`` with ``converged=False``).

Parity-config note
------------------
Two solve routes are covered (the M1 production-config parity gap D-J8-1):

* the **shared-math** ``raw`` preset (``saha_boltzmann_graph=False`` +
  ``stark_ne=False`` + ``standard`` closure, via ``_PARITY_OVERRIDES``): the jit
  ``scan_solve`` mirrors the reference ``_solve_lax`` fixed point bit-for-bit
  (with ``CFLIBS_USE_LAX_WHILE_LOOP=1`` the reference uses the bit-exact lax
  oracle); and
* the **production geological/metallic** preset
  (``saha_boltzmann_graph=True`` + ``stark_ne=True``): the reference routes
  ``_solve_python``'s unit-weight SB-graph with ``n_e`` pinned to the Stark
  measurement, which the jit composition now mirrors via
  :func:`cflibs.jitpipe.solve.production_solve` (the ``scan_solve`` initializer
  SEEDS :func:`joint_wls_solve`, ``sb_graph=True``). These cases
  (``test_run_one_matches_reference_production_*``) close D-J8-1 — the M1 gate
  is COMPOSITION parity under the SAME geological preset on both sides.

Data
----
Synthetic spectra are generated by the deterministic CF-LIBS forward model (no
external data). A real ChemCam BHVO-2 fixture is used when present
(``data/bhvo2_usgs/chemcam_bhvo2_loc1_spectrum.csv``, tracked in this
worktree); skipped gracefully if absent.

CPU x64 (conftest forces ``jax_enable_x64``); a narrow subset per the watchdog
rules in CLAUDE.md.
"""

from __future__ import annotations

import os
from pathlib import Path

import numpy as np
import pytest

os.environ.setdefault("JAX_PLATFORMS", "cpu")

jax = pytest.importorskip("jax")
jax.config.update("jax_enable_x64", True)

pytestmark = [pytest.mark.requires_jax, pytest.mark.requires_db, pytest.mark.integration]


@pytest.fixture(autouse=True)
def _enable_lax_while_loop(monkeypatch):
    """Pin the reference to the bit-exact lax fixed point these parity tests
    mirror. Set via ``monkeypatch`` (auto-restored per test) instead of a
    module-level ``os.environ.setdefault``, which leaked
    ``CFLIBS_USE_LAX_WHILE_LOOP=1`` into the whole pytest session AT COLLECTION
    TIME and silently switched every later solver test to the JAX lax path —
    the root cause of the cumulative, full-suite-only failures in the Stark
    pressure-balance-fallback caplog tests and the multistage pipeline_e2e
    recovery.
    """
    monkeypatch.setenv("CFLIBS_USE_LAX_WHILE_LOOP", "1")

DB_PATH = "ASD_da/libs_production.db"
_REPO_ROOT = Path(__file__).resolve().parents[2]
_REAL_SPECTRUM = _REPO_ROOT / "data" / "bhvo2_usgs" / "chemcam_bhvo2_loc1_spectrum.csv"

# Parity config: the shared solve math path (see module docstring).
_PARITY_OVERRIDES = {
    "closure_mode": "standard",
    "saha_boltzmann_graph": False,
    "stark_ne": False,
    "response_curve": None,
}


@pytest.fixture(scope="module")
def db():
    from cflibs.atomic.database import AtomicDatabase

    if not Path(DB_PATH).exists():  # pragma: no cover - env-dependent
        pytest.skip(f"atomic DB not present at {DB_PATH}")
    return AtomicDatabase(DB_PATH)


@pytest.fixture(scope="module")
def snapshot():
    from cflibs.jitpipe import build_snapshot

    if not Path(DB_PATH).exists():  # pragma: no cover
        pytest.skip(f"atomic DB not present at {DB_PATH}")
    return build_snapshot(DB_PATH)


def _static_for(snapshot, closure_mode="standard", max_iters=20):
    from cflibs.jitpipe import StaticConfig

    return StaticConfig(
        bucket_id=0,
        n_species=snapshot.n_species,
        level_pad=snapshot.level_pad[1],
        closure_mode=closure_mode,
        max_iters=max_iters,
    )


def _synthetic_spectrum(db, T_K=9000.0, n_e=2.0e16, lam=(240.0, 450.0), dlam=0.02):
    """Deterministic synthetic spectrum via the CF-LIBS forward model."""
    from cflibs.instrument.model import InstrumentModel
    from cflibs.plasma.state import SingleZoneLTEPlasma
    from cflibs.radiation.spectrum_model import SpectrumModel

    species = {"Fe": 5.0e15, "Ca": 3.0e15, "Ti": 2.0e15}
    plasma = SingleZoneLTEPlasma(T_e=T_K, n_e=n_e, species=species)
    instr = InstrumentModel(resolution_fwhm_nm=0.05)
    model = SpectrumModel(plasma, db, instr, lam[0], lam[1], dlam)
    wl, inten = model.compute_spectrum()
    return np.asarray(wl, float), np.asarray(inten, float), list(species.keys())


def _load_real_spectrum():
    rows = np.genfromtxt(_REAL_SPECTRUM, delimiter=",", names=True)
    return np.asarray(rows["wavelength"], float), np.asarray(rows["intensity"], float)


def _assert_m1_parity(ref, got, *, elements):
    """Assert the M1 tolerances between a reference and jit CFLIBSResult."""
    # 1. Element calls agree (every present element must match here).
    ref_calls = {k for k, v in ref.concentrations.items() if v > 0.0}
    got_calls = {k for k, v in got.concentrations.items() if v > 0.0}
    assert got_calls == ref_calls, f"element calls differ: jit={got_calls} ref={ref_calls}"

    # 2. T within 2 %, n_e within 10 %.
    np.testing.assert_allclose(got.temperature_K, ref.temperature_K, rtol=0.02)
    np.testing.assert_allclose(got.electron_density_cm3, ref.electron_density_cm3, rtol=0.10)

    # 3. Per-element concentration rtol 5 % / atol 0.01.
    for el in ref.concentrations:
        np.testing.assert_allclose(
            got.concentrations.get(el, 0.0),
            ref.concentrations[el],
            rtol=0.05,
            atol=0.01,
            err_msg=f"concentration parity failed for {el}",
        )


# ---------------------------------------------------------------------------
# 1. Synthetic end-to-end composition parity (no external data).
# ---------------------------------------------------------------------------


def test_run_one_matches_reference_synthetic(db, snapshot):
    """run_one reproduces run_pipeline end-to-end on a synthetic spectrum.

    Exercises the full COMPOSITION: response/preprocess -> calibrate -> detect
    + identify -> solve. This case pins the **reference-delegated** front-end
    (``ondevice_front_end=False``) so it stays a stable baseline alongside the
    on-device-front-end cases below (the Wave-3 deliverable). The solve spine
    runs the jit ``scan_solve`` kernel; the reference runs its own solve on the
    same observations. M1 tolerances.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
        ondevice_front_end=False,
    )
    _assert_m1_parity(ref, got, elements=elements)


def test_run_one_returns_cflibs_result_type(db, snapshot):
    """run_one returns the SAME ``CFLIBSResult`` dataclass the reference returns."""
    from cflibs.inversion.pipeline import build_pipeline_config
    from cflibs.inversion.solve.iterative import CFLIBSResult
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)
    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
    )
    assert isinstance(got, CFLIBSResult)
    assert set(got.concentrations) == set(elements)


# ---------------------------------------------------------------------------
# 2. Real ChemCam BHVO-2 end-to-end parity (when the fixture is present).
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not _REAL_SPECTRUM.exists(), reason="real ChemCam BHVO-2 fixture not present in worktree"
)
def test_run_one_matches_reference_real_chemcam(db, snapshot):
    """run_one reproduces run_pipeline on a REAL ChemCam BHVO-2 spectrum (M1 headline).

    Reference-delegated front-end baseline (``ondevice_front_end=False``); the
    on-device counterpart is ``test_ondevice_*`` below.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten = _load_real_spectrum()
    elements = ["Si", "Ti", "Al", "Fe", "Mn", "Mg", "Ca", "Na", "K"]
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
        ondevice_front_end=False,
    )
    _assert_m1_parity(ref, got, elements=elements)


# ---------------------------------------------------------------------------
# 2b. PRODUCTION geological/metallic preset parity (divergence D-J8-1).
#
# The production preset (``saha_boltzmann_graph=True`` + ``stark_ne=True``)
# routes the reference solve through ``_solve_python``'s unit-weight
# Saha-Boltzmann graph with ``n_e`` pinned to the Stark measurement — the path
# the shared-math ``scan_solve`` does NOT mirror. ``run_one`` now routes this
# preset through :func:`cflibs.jitpipe.solve.production_solve` (the scan
# initializer SEEDS :func:`joint_wls_solve`, ``sb_graph=True``). These cases
# prove ``run_one`` bit-matches the reference UNDER THE GEOLOGICAL PRESET
# (ADR-0004 §6.1; J7 §4 row 10). No ``_PARITY_OVERRIDES``: the preset's own
# SB-graph + Stark flags drive both sides.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("preset", "closure_mode"),
    [("geological", "oxide"), ("metallic", "standard")],
)
def test_run_one_matches_reference_production_synthetic(db, snapshot, preset, closure_mode):
    """run_one == run_pipeline under the PRODUCTION preset on a synthetic spectrum.

    Both sides resolve the same ``geological``/``metallic`` preset
    (``saha_boltzmann_graph=True`` + ``stark_ne=True``); the reference routes
    ``_solve_python`` (SB-graph + Stark-pinned n_e), the jit composition routes
    :func:`production_solve` (scan-seeded joint WLS). M1 tolerances.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten, elements = _synthetic_spectrum(db)
    # Build the preset faithfully — no SB-graph/Stark overrides (D-J8-1 path).
    cfg = build_pipeline_config(elements, preset=preset)
    assert cfg.saha_boltzmann_graph is True
    assert cfg.stark_ne is True

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot, closure_mode=closure_mode),
        atomic_db=db,
        pipeline_config=cfg,
        ondevice_front_end=False,
    )
    _assert_m1_parity(ref, got, elements=elements)


@pytest.mark.skipif(
    not _REAL_SPECTRUM.exists(), reason="real ChemCam BHVO-2 fixture not present in worktree"
)
def test_run_one_matches_reference_production_real_chemcam(db, snapshot):
    """run_one == run_pipeline under the GEOLOGICAL preset on REAL ChemCam BHVO-2.

    The M1 headline acceptance case: the production geological preset
    (``saha_boltzmann_graph=True`` + ``closure_mode='oxide'`` + ``stark_ne=True``)
    on the real ChemCam BHVO-2 spectrum, asserting element calls >= 95 %, T
    within 2 %, n_e within 10 %, per-element concentration rtol 5 % / atol 0.01.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten = _load_real_spectrum()
    elements = ["Si", "Ti", "Al", "Fe", "Mn", "Mg", "Ca", "Na", "K"]
    cfg = build_pipeline_config(elements, preset="geological")
    assert cfg.saha_boltzmann_graph is True
    assert cfg.closure_mode == "oxide"

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0
    assert ref.converged

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot, closure_mode="oxide"),
        atomic_db=db,
        pipeline_config=cfg,
        ondevice_front_end=False,
    )
    assert got.converged
    # Element-call agreement >= 95 % (here all present elements must match).
    ref_calls = {k for k, v in ref.concentrations.items() if v > 0.0}
    got_calls = {k for k, v in got.concentrations.items() if v > 0.0}
    assert len(ref_calls) > 0
    n_agree = len(ref_calls & got_calls) + len({e for e in elements} - ref_calls - got_calls)
    assert n_agree / len(elements) >= 0.95, f"calls: jit={got_calls} ref={ref_calls}"
    _assert_m1_parity(ref, got, elements=elements)


def test_failure_policy_parity_production(db, snapshot):
    """Geological-preset failure policy: flat spectrum -> same all-FN record.

    Failure-policy parity (AC4) must hold on the production route too: the
    reference raises ``ValueError`` at zero observations; the jit pipeline
    returns the all-FN ``CFLIBSResult`` (``converged=False``, all-zero conc).
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl = np.arange(240.0, 450.0, 0.02)
    flat = np.ones_like(wl)
    elements = ["Fe", "Ca", "Ti"]
    cfg = build_pipeline_config(elements, preset="geological")

    with pytest.raises(ValueError, match="No usable spectral lines"):
        run_pipeline(wl, flat, db, cfg)

    got = run_one(
        flat,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot, closure_mode="oxide"),
        atomic_db=db,
        pipeline_config=cfg,
    )
    assert got.converged is False
    assert set(got.concentrations) == set(elements)
    assert all(v == 0.0 for v in got.concentrations.values())
    assert np.isfinite(got.temperature_K)
    assert np.isfinite(got.electron_density_cm3)


# ---------------------------------------------------------------------------
# 3. Failure-policy parity (AC4): zero usable lines -> same all-FN record.
# ---------------------------------------------------------------------------


def test_failure_policy_parity(db, snapshot):
    """A flat (peak-free) spectrum: reference raises ValueError, jit returns all-FN.

    The reference scoreboard scores the ValueError as all false-negative; the
    jit pipeline must emit the same all-FN record (NaN-free, ``converged=False``,
    element keys preserved) — not a crash, not NaN.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl = np.arange(240.0, 450.0, 0.02)
    flat = np.ones_like(wl)
    elements = ["Fe", "Ca", "Ti"]
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)

    # Reference: zero observations -> ValueError.
    with pytest.raises(ValueError, match="No usable spectral lines"):
        run_pipeline(wl, flat, db, cfg)

    # Jit: same all-FN record (no crash, no NaN).
    got = run_one(
        flat,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
    )
    assert got.converged is False
    assert set(got.concentrations) == set(elements)
    assert all(v == 0.0 for v in got.concentrations.values())
    assert np.isfinite(got.temperature_K)
    assert np.isfinite(got.electron_density_cm3)
    assert not any(np.isnan(v) for v in got.concentrations.values())


# ---------------------------------------------------------------------------
# 4. run_batch host-loop produces per-spectrum CFLIBSResults.
# ---------------------------------------------------------------------------


def test_run_batch_host_loop(db, snapshot):
    """run_batch returns one CFLIBSResult per spectrum (J8 host loop; vmap in J9)."""
    from cflibs.inversion.pipeline import build_pipeline_config
    from cflibs.inversion.solve.iterative import CFLIBSResult
    from cflibs.jitpipe import PipelineParams, run_batch

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)
    batch = np.stack([inten, inten * 1.001])  # two near-identical spectra
    results = run_batch(
        batch,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_configs=[cfg, cfg],
    )
    assert len(results) == 2
    assert all(isinstance(r, CFLIBSResult) for r in results)
    assert all(set(r.concentrations) == set(elements) for r in results)


# ---------------------------------------------------------------------------
# 5. solve-stage padding invariance at the composition level (AC5/AC6 surface).
# ---------------------------------------------------------------------------


def test_solve_stage_bucket_invariance(db, snapshot):
    """A larger static max_iters bucket leaves the answer unchanged (idempotent freeze)."""
    from cflibs.inversion.pipeline import build_pipeline_config
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)
    params = PipelineParams()

    r20 = run_one(
        inten,
        wl,
        snapshot,
        params,
        _static_for(snapshot, max_iters=20),
        atomic_db=db,
        pipeline_config=cfg,
    )
    r30 = run_one(
        inten,
        wl,
        snapshot,
        params,
        _static_for(snapshot, max_iters=30),
        atomic_db=db,
        pipeline_config=cfg,
    )
    # The converged-state freeze makes scan_solve idempotent past convergence.
    np.testing.assert_allclose(r30.temperature_K, r20.temperature_K, rtol=1e-9)
    for el in elements:
        np.testing.assert_allclose(
            r30.concentrations[el], r20.concentrations[el], rtol=1e-9, atol=1e-12
        )


# ---------------------------------------------------------------------------
# 6. ON-DEVICE FRONT-END parity (Wave 3 / 3b, the J9/M2 prerequisite; ADR R8).
#
# ``run_one(ondevice_front_end=True)`` runs the detect + identify gate stack as
# the parity-tested JIT kernels (J1 detect, J3 comb scan / shift select / veto /
# observation build, trapezoid intensity) instead of byte-for-byte delegating to
# the reference ``detect_and_select_lines``. Wave 3b additionally moves the
# **kdet pre-filter** (coherence branch, J3 ``kdet_keep_mask``) and the
# post-detection **LineSelector** (SNR / isolation / score on a fixed-shape
# kernel) on-device. The catalog SQL + gA-Boltzmann comb ranking stay host-side;
# the segmented wavelength calibration and the Stark n_e diagnostic stay
# reference-delegated (segmented calibration is composed on-device as
# ``calibrate_segmented_kernel`` but is too slow + diverges on the real ChemCam
# confounder at production widths — the J2 §7 R8 hazard — so the byte-faithful
# reference is kept; Stark stays delegated to protect the n_e pin; see
# ``cflibs/jitpipe/host.py`` module note). The CONTRACT is that the on-device
# gate stack reproduces the reference front-end observation set (accepted
# elements + line-keys, floor Jaccard >= 0.98) AND that ``run_one`` stays within
# the M1 end-to-end tolerances.
# ---------------------------------------------------------------------------


def _ref_front_end_obs(db, wl, inten, cfg):
    """Run the REAL reference ``detect_and_select_lines`` front-end (parity oracle)."""
    from cflibs.inversion.pipeline import detect_and_select_lines

    observations, _diag = detect_and_select_lines(
        wl,
        inten,
        db,
        cfg.elements,
        min_relative_intensity=cfg.min_relative_intensity,
        top_k_per_element=cfg.top_k_per_element,
        resolving_power=cfg.resolving_power,
        wavelength_tolerance_nm=cfg.wavelength_tolerance_nm,
        min_peak_height=cfg.min_peak_height,
        peak_width_nm=cfg.peak_width_nm,
        apply_self_absorption=cfg.apply_self_absorption,
        exclude_resonance=cfg.exclude_resonance,
        min_snr=cfg.min_snr,
        min_energy_spread_ev=cfg.min_energy_spread_ev,
        min_lines_per_element=cfg.min_lines_per_element,
        isolation_wavelength_nm=cfg.isolation_wavelength_nm,
        max_lines_per_element=cfg.max_lines_per_element,
        wavelength_calibration=cfg.wavelength_calibration,
        shift_coherence_veto=cfg.shift_coherence_veto,
        residual_shift_scan_nm=cfg.residual_shift_scan_nm,
        global_shift_scan_nm=cfg.global_shift_scan_nm,
        affine_coverage_gate=cfg.affine_coverage_gate,
        line_residual_gate=cfg.line_residual_gate,
        detection_overrides=cfg.detection_overrides,
        return_diagnostics=True,
    )
    return observations


def _obs_line_keys(observations):
    return {(o.element, o.ionization_stage, round(o.wavelength_nm, 4)) for o in observations}


def _jaccard(a, b):
    union = len(a | b)
    return 1.0 if union == 0 else len(a & b) / union


@pytest.mark.parametrize("preset", ["raw", "geological"])
def test_ondevice_front_end_matches_reference_obs_synthetic(db, snapshot, preset):
    """ON-DEVICE front-end observation set == reference front-end (synthetic).

    The Wave-3 contract: the on-device J1-detect + J3-identify gate stack
    reproduces the reference ``detect_and_select_lines`` accepted-element set and
    observation line-keys (floor Jaccard >= 0.98 — here exact).
    """
    from cflibs.inversion.pipeline import build_pipeline_config
    from cflibs.jitpipe.host import run_front_end_ondevice

    wl, inten, elements = _synthetic_spectrum(db)
    overrides = _PARITY_OVERRIDES if preset == "raw" else None
    cfg = build_pipeline_config(elements, preset=preset, overrides=overrides)

    ref_obs = _ref_front_end_obs(db, wl, inten, cfg)
    dev = run_front_end_ondevice(wl, inten, db, cfg, snapshot)

    ref_keys = _obs_line_keys(ref_obs)
    dev_keys = _obs_line_keys(dev.observations)
    assert {o.element for o in ref_obs} == {o.element for o in dev.observations}
    assert _jaccard(ref_keys, dev_keys) >= 0.98, (
        f"line-key Jaccard < 0.98 for preset={preset}: "
        f"only_ref={sorted(ref_keys - dev_keys)[:8]} only_dev={sorted(dev_keys - ref_keys)[:8]}"
    )


@pytest.mark.skipif(
    not _REAL_SPECTRUM.exists(), reason="real ChemCam BHVO-2 fixture not present in worktree"
)
@pytest.mark.parametrize("preset", ["raw", "geological"])
def test_ondevice_front_end_matches_reference_obs_real_chemcam(db, snapshot, preset):
    """ON-DEVICE front-end observation set == reference front-end (real BHVO-2).

    The highest-concentration hazard (ADR R8): the BHVO-2 confounder spectrum
    fires the residual gate + min-kept-bars drop (Sn/Th class). The on-device
    gate stack must reproduce the reference accepted/kept element set + line-keys
    (floor Jaccard >= 0.98).
    """
    from cflibs.inversion.pipeline import build_pipeline_config
    from cflibs.jitpipe.host import run_front_end_ondevice

    wl, inten = _load_real_spectrum()
    elements = ["Si", "Ti", "Al", "Fe", "Mn", "Mg", "Ca", "Na", "K"]
    overrides = _PARITY_OVERRIDES if preset == "raw" else None
    cfg = build_pipeline_config(elements, preset=preset, overrides=overrides)

    ref_obs = _ref_front_end_obs(db, wl, inten, cfg)
    dev = run_front_end_ondevice(wl, inten, db, cfg, snapshot)

    ref_keys = _obs_line_keys(ref_obs)
    dev_keys = _obs_line_keys(dev.observations)
    assert {o.element for o in ref_obs} == {o.element for o in dev.observations}
    assert _jaccard(ref_keys, dev_keys) >= 0.98, (
        f"line-key Jaccard < 0.98 for preset={preset}: "
        f"only_ref={sorted(ref_keys - dev_keys)[:8]} only_dev={sorted(dev_keys - ref_keys)[:8]}"
    )


def test_ondevice_run_one_matches_reference_synthetic(db, snapshot):
    """run_one(ondevice_front_end=True) == run_pipeline end-to-end (synthetic, raw).

    The full on-device composition: J1 detect + J3 identify gate stack -> jit
    ``scan_solve`` -> ``CFLIBSResult``. M1 tolerances vs the reference.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
        ondevice_front_end=True,
    )
    _assert_m1_parity(ref, got, elements=elements)


@pytest.mark.skipif(
    not _REAL_SPECTRUM.exists(), reason="real ChemCam BHVO-2 fixture not present in worktree"
)
def test_ondevice_run_one_matches_reference_real_chemcam(db, snapshot):
    """run_one(ondevice_front_end=True) == run_pipeline on REAL BHVO-2 (raw preset)."""
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten = _load_real_spectrum()
    elements = ["Si", "Ti", "Al", "Fe", "Mn", "Mg", "Ca", "Na", "K"]
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
        ondevice_front_end=True,
    )
    _assert_m1_parity(ref, got, elements=elements)


@pytest.mark.skipif(
    not _REAL_SPECTRUM.exists(), reason="real ChemCam BHVO-2 fixture not present in worktree"
)
def test_ondevice_run_one_matches_reference_production_real_chemcam(db, snapshot):
    """run_one(ondevice_front_end=True) == run_pipeline on REAL BHVO-2 (GEOLOGICAL).

    The Wave-3 M1 headline: the production geological preset
    (``saha_boltzmann_graph=True`` + ``closure_mode='oxide'`` + ``stark_ne=True``)
    with the ON-DEVICE front-end on the real ChemCam BHVO-2 confounder spectrum.
    Element calls >= 95 %, T within 2 %, n_e within 10 %, conc rtol 5 % / atol
    0.01 — the same gate the reference-delegated case meets, now with the gate
    stack running as JIT kernels.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten = _load_real_spectrum()
    elements = ["Si", "Ti", "Al", "Fe", "Mn", "Mg", "Ca", "Na", "K"]
    cfg = build_pipeline_config(elements, preset="geological")
    assert cfg.saha_boltzmann_graph is True
    assert cfg.closure_mode == "oxide"

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0
    assert ref.converged

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot, closure_mode="oxide"),
        atomic_db=db,
        pipeline_config=cfg,
        ondevice_front_end=True,
    )
    assert got.converged
    ref_calls = {k for k, v in ref.concentrations.items() if v > 0.0}
    got_calls = {k for k, v in got.concentrations.items() if v > 0.0}
    assert len(ref_calls) > 0
    n_agree = len(ref_calls & got_calls) + len({e for e in elements} - ref_calls - got_calls)
    assert n_agree / len(elements) >= 0.95, f"calls: jit={got_calls} ref={ref_calls}"
    _assert_m1_parity(ref, got, elements=elements)


def test_ondevice_failure_policy_parity(db, snapshot):
    """ON-DEVICE front-end failure policy: flat spectrum -> same all-FN record (AC4)."""
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl = np.arange(240.0, 450.0, 0.02)
    flat = np.ones_like(wl)
    elements = ["Fe", "Ca", "Ti"]
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)

    with pytest.raises(ValueError, match="No usable spectral lines"):
        run_pipeline(wl, flat, db, cfg)

    got = run_one(
        flat,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
        ondevice_front_end=True,
    )
    assert got.converged is False
    assert set(got.concentrations) == set(elements)
    assert all(v == 0.0 for v in got.concentrations.values())
    assert np.isfinite(got.temperature_K)
    assert np.isfinite(got.electron_density_cm3)


# ---------------------------------------------------------------------------
# 6b. ON-DEVICE segmented WAVELENGTH CALIBRATION (J9 / J2 §7 R8).
#
# The segmented calibration now runs on-device in ``run_front_end_ondevice``
# (the kernel-backed driver ``_ondevice_calibrate_segmented``: the reference
# segmented-driver structure with every robust RANSAC core routed through the J2
# ``calibrate_axis_kernel``). These pin:
#   (1) the corrected axis matches the reference ``calibrate_wavelength_axis_segmented``
#       within the J2 contract (sub-pixel; max|Δλ| <= 0.04 nm) on the real BHVO-2
#       confounder, raw + geological presets;
#   (2) the J2 §7 R8 model-flip is closed — the ye6t BHVO-2 877 nm Al doublet is
#       NOT dropped (the per-segment shift/affine decision matches the reference,
#       so the corrected red end keeps the Al 877.3896 nm line, obs Jaccard 1.0).
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not _REAL_SPECTRUM.exists(), reason="real ChemCam BHVO-2 fixture not present in worktree"
)
@pytest.mark.parametrize("preset", ["raw", "geological"])
def test_ondevice_calibration_axis_matches_reference_real_chemcam(db, preset):
    """ON-DEVICE segmented calibration corrected axis == reference (real BHVO-2).

    Feeds the SAME (wavelength, intensity) to the reference
    ``calibrate_wavelength_axis_segmented`` and the kernel-backed on-device driver
    ``_ondevice_calibrate_segmented`` and asserts the J2 §4 corrected-axis
    contract: ``max|λ_dev − λ_ref| <= inlier_tolerance_nm/2 = 0.04 nm`` (sub-pixel)
    over the whole axis. The real ChemCam BHVO-2 confounder is the J2 §7 R8 hazard
    (a 53 %-anchored seg-2 affine that the kernel's stronger search finds but the
    dense-hull tiebreak degrades to shift, matching the reference).
    """
    from cflibs.inversion.pipeline import build_pipeline_config
    from cflibs.inversion.preprocess.wavelength_calibration import (
        calibrate_wavelength_axis_segmented,
    )

    from cflibs.jitpipe.host import _ondevice_calibrate_segmented

    wl, inten = _load_real_spectrum()
    elements = ["Si", "Ti", "Al", "Fe", "Mn", "Mg", "Ca", "Na", "K"]
    cfg = build_pipeline_config(
        elements, preset=preset, overrides=_PARITY_OVERRIDES if preset == "raw" else None
    )

    ref = calibrate_wavelength_axis_segmented(
        wavelength=wl,
        intensity=inten,
        atomic_db=db,
        elements=elements,
        affine_coverage_gate=cfg.affine_coverage_gate,
    )
    dev_corr, dev_success, dev_quality = _ondevice_calibrate_segmented(wl, inten, db, elements, cfg)

    assert ref.success and dev_success
    assert ref.quality_passed == dev_quality
    ref_corr = np.asarray(ref.corrected_wavelength, dtype=float)
    max_dev = float(np.max(np.abs(dev_corr - ref_corr)))
    assert (
        max_dev <= 0.04
    ), f"corrected-axis divergence {max_dev:.5f} nm > 0.04 nm (preset={preset})"


@pytest.mark.skipif(
    not _REAL_SPECTRUM.exists(), reason="real ChemCam BHVO-2 fixture not present in worktree"
)
@pytest.mark.parametrize("preset", ["raw", "geological"])
def test_ondevice_calibration_ye6t_al_doublet_not_dropped(db, snapshot, preset):
    """J2 §7 R8 confounder: the ON-DEVICE-calibrated front-end keeps the Al doublet.

    The named regression: with the OLD monolithic ``calibrate_segmented_kernel``
    the BHVO-2 seg-2 affine/shift model-class flip shifted the corrected axis
    ~0.1 nm at the red end, moving the Al I 877.3896 nm doublet member to the
    wrong wavelength (877.2866) and dropping the reference line key (obs Jaccard
    fell to ~0.96 on raw). With the kernel-backed driver + the unconditional
    dense-hull tiebreak the corrected axis matches the reference, so:

      * the reference Al observation set == the on-device set, AND
      * the Al 877.3896 nm line is present on the on-device side.
    """
    from cflibs.inversion.pipeline import build_pipeline_config

    from cflibs.jitpipe.host import run_front_end_ondevice

    wl, inten = _load_real_spectrum()
    elements = ["Si", "Ti", "Al", "Fe", "Mn", "Mg", "Ca", "Na", "K"]
    cfg = build_pipeline_config(
        elements, preset=preset, overrides=_PARITY_OVERRIDES if preset == "raw" else None
    )

    ref_obs = _ref_front_end_obs(db, wl, inten, cfg)
    dev = run_front_end_ondevice(wl, inten, db, cfg, snapshot)

    ref_keys = _obs_line_keys(ref_obs)
    dev_keys = _obs_line_keys(dev.observations)
    # Whole-set Jaccard contract (the ye6t case is the binding floor).
    assert _jaccard(ref_keys, dev_keys) >= 0.98, (
        f"obs Jaccard < 0.98 (preset={preset}): "
        f"only_ref={sorted(ref_keys - dev_keys)[:8]} only_dev={sorted(dev_keys - ref_keys)[:8]}"
    )
    # The Al-doublet member specifically must not be dropped (the R8 signature).
    ref_al = {k for k in ref_keys if k[0] == "Al"}
    dev_al = {k for k in dev_keys if k[0] == "Al"}
    assert (
        ref_al == dev_al
    ), f"Al observation set differs (preset={preset}): ref={ref_al} dev={dev_al}"
    al_877 = ("Al", 1, 877.3896)
    if al_877 in ref_al:
        assert (
            al_877 in dev_al
        ), "ye6t Al 877.3896 nm doublet member dropped by on-device calibration"


# ---------------------------------------------------------------------------
# 7. Wave-3b stage parity: the two stages newly moved on-device, asserted in
# isolation against their REFERENCE counterparts (fast — no segmented kernel).
#
#  * kdet pre-filter (coherence branch) -> ``_ondevice_kdet_filter`` (J3
#    ``kdet_keep_mask``) vs the reference ``_apply_kdet_filter``;
#  * LineSelector (SNR / isolation / score / top-K) -> ``_ondevice_line_select``
#    (fixed-shape ``_line_selector_scores`` kernel) vs ``LineSelector.select``.
#
# These pin the newly-on-device stages directly; the end-to-end Jaccard + M1
# tolerances above remain the integration contract.
# ---------------------------------------------------------------------------


def test_ondevice_kdet_filter_matches_reference(db):
    """ON-DEVICE kdet coherence filter == reference ``_apply_kdet_filter`` (BHVO-2).

    The coherence branch (``shift_coherence_veto=True``, the pipeline default)
    runs the J3 ``kdet_keep_mask`` kernel on a full-transition-set snapshot. On
    the real ChemCam BHVO-2 spectrum it must keep the SAME element set the
    reference Rust/NumPy filter keeps, with identical per-element transition
    counts.
    """
    import copy

    from cflibs.inversion.identify import line_detection as _ld
    from cflibs.inversion.preprocess.preprocessing import detect_peaks_auto

    from cflibs.jitpipe.host import _ondevice_kdet_filter

    if not _REAL_SPECTRUM.exists():  # pragma: no cover - env-dependent
        pytest.skip("real ChemCam BHVO-2 fixture not present")
    wl, inten = _load_real_spectrum()
    elements = ["Si", "Ti", "Al", "Fe", "Mn", "Mg", "Ca", "Na", "K"]

    peaks, _b, _n = detect_peaks_auto(wl, inten, threshold_factor=4.0)
    trans = _ld._load_transitions(
        db,
        elements,
        wavelength_min=float(wl.min()),
        wavelength_max=float(wl.max()),
        min_relative_intensity=0.001,
        top_k_per_element=None,
    )
    tbe: dict = {}
    for t in trans:
        tbe.setdefault(t.element, []).append(t)

    tol = 0.1
    wl_step = float(np.median(np.diff(wl)))
    ref = _ld._apply_kdet_filter(
        peaks=peaks,
        transitions_by_element=copy.deepcopy(tbe),
        shift_scan_nm=0.5,
        shift_step_nm=None,
        wavelength_tolerance_nm=tol,
        wl_step=wl_step,
        kdet_min_score=0.05,
        kdet_min_candidates=2,
        kdet_rarity_power=0.5,
        kdet_weight_clip=(0.25, 4.0),
        use_jax_kdet=False,
        shift_coherence_veto=True,
        coherence_min_lines=2,
        coherence_min_fraction=0.5,
        warnings=[],
    )
    dev = _ondevice_kdet_filter(
        peaks,
        tbe,
        shift_scan_nm=0.5,
        wl_step=wl_step,
        tolerance_nm=tol,
        shift_coherence_veto=True,
    )
    assert set(dev.keys()) == set(ref.keys()), (sorted(dev), sorted(ref))
    for el in ref:
        assert len(dev[el]) == len(ref[el]), (el, len(dev[el]), len(ref[el]))


def test_ondevice_kdet_density_branch_falls_back():
    """Density-score branch (``shift_coherence_veto=False``) is NOT ported -> None.

    That branch dispatches to Rust + a density score the J3 kernel does not
    port; the on-device helper must return ``None`` so the caller falls back to
    the reference filter (no silent divergence).
    """
    from cflibs.jitpipe.host import _ondevice_kdet_filter

    peaks = [(10, 400.0), (20, 410.0)]
    tbe = {"Fe": []}
    assert (
        _ondevice_kdet_filter(
            peaks,
            tbe,
            shift_scan_nm=0.5,
            wl_step=0.05,
            tolerance_nm=0.1,
            shift_coherence_veto=False,
        )
        is None
    )


@pytest.mark.parametrize("exclude_resonance", [False, True])
def test_ondevice_line_select_matches_reference(exclude_resonance):
    """ON-DEVICE ``_ondevice_line_select`` == reference ``LineSelector.select``.

    Bit-faithful selected-line set AND order (the order feeds Stark/solve) on a
    synthetic multi-element observation list, with and without resonance
    exclusion. The score kernel runs on-device; the gate + per-element top-K cap
    are applied in the reference order on the host.
    """
    from cflibs.inversion.common import LineObservation
    from cflibs.inversion.physics.line_selection import LineSelector

    from cflibs.jitpipe.host import _ondevice_line_select

    rng = np.random.default_rng(7)
    observations = []
    resonance_lines = set()
    for el in ("Fe", "Ca", "Ti"):
        for k in range(8):
            wl = 400.0 + rng.uniform(0.0, 40.0)
            obs = LineObservation(
                wavelength_nm=wl,
                intensity=rng.uniform(50.0, 500.0),
                intensity_uncertainty=rng.uniform(1.0, 20.0),
                element=el,
                ionization_stage=1,
                E_k_ev=rng.uniform(2.0, 6.0),
                g_k=3.0,
                A_ki=1e7,
                aki_uncertainty=0.1,
            )
            observations.append(obs)
            if k == 0:
                resonance_lines.add((el, 1, wl))

    class _Cfg:
        min_snr = 10.0
        min_energy_spread_ev = 2.0
        min_lines_per_element = 2
        isolation_wavelength_nm = 0.1
        max_lines_per_element = 4

    selector = LineSelector(
        min_snr=_Cfg.min_snr,
        min_energy_spread_ev=_Cfg.min_energy_spread_ev,
        min_lines_per_element=_Cfg.min_lines_per_element,
        exclude_resonance=exclude_resonance,
        isolation_wavelength_nm=_Cfg.isolation_wavelength_nm,
        max_lines_per_element=_Cfg.max_lines_per_element,
    )
    ref = selector.select(observations, resonance_lines=resonance_lines).selected_lines
    dev = _ondevice_line_select(observations, resonance_lines, _Cfg, exclude_resonance)

    ref_keys = [(o.element, round(o.wavelength_nm, 6)) for o in ref]
    dev_keys = [(o.element, round(o.wavelength_nm, 6)) for o in dev]
    assert dev_keys == ref_keys, (dev_keys, ref_keys)
