"""End-to-end parity tests for the J8 jit pipeline composition (ADR-0004 §8.1, M1).

Feeds IDENTICAL inputs to :func:`cflibs.jitpipe.run_one` and the REAL reference
:func:`cflibs.inversion.pipeline.run_pipeline` and asserts the M1 tolerances:

* element calls agree (>= 95 % of spectra; here every element call must match),
* T within 2 %, n_e within 10 %,
* per-element concentration rtol 5 % / atol 0.01,
* failure-policy parity: a spectrum with zero usable lines produces the same
  all-FN scored record on both pipelines (the reference raises ``ValueError``;
  the jit pipeline returns an all-zero ``CFLIBSResult`` with ``converged=False``).

Parity-config note
------------------
The production geological preset routes the reference solve through the
SB-graph Python path (``saha_boltzmann_graph=True`` + ``stark_ne=True`` force
``_solve_python``). The J8 jit solve spine (``scan_solve``) mirrors the
``_solve_lax`` fixed point, which is itself parity-tested against
``_solve_python`` for the *standard*-closure, SB-graph-OFF path
(``test_iterative_lax.py``). So these end-to-end parity tests pin the reference
to that shared math path (``saha_boltzmann_graph=False``, ``stark_ne=False``,
``standard`` closure) where the composition comparison is exact. With
``CFLIBS_USE_LAX_WHILE_LOOP=1`` the reference uses the bit-exact lax oracle.

The full production-config solve (SB-graph + oxide + Stark-pinned n_e) is a
J8.5+ deliverable (``joint_wls_solve`` is the production estimator); the M1 gate
here is exact COMPOSITION parity on the shared solve math.

Data
----
Synthetic spectra are generated by the deterministic CF-LIBS forward model (no
external data). A real ChemCam BHVO-2 fixture is used when present
(``data/bhvo2_usgs/chemcam_bhvo2_loc1_spectrum.csv``, tracked in this
worktree); skipped gracefully if absent.

CPU x64 (conftest forces ``jax_enable_x64``); a narrow subset per the watchdog
rules in CLAUDE.md.
"""

from __future__ import annotations

import os
from pathlib import Path

import numpy as np
import pytest

os.environ.setdefault("JAX_PLATFORMS", "cpu")
# Pin the reference to the bit-exact lax fixed point that scan_solve mirrors.
os.environ.setdefault("CFLIBS_USE_LAX_WHILE_LOOP", "1")

jax = pytest.importorskip("jax")
jax.config.update("jax_enable_x64", True)

pytestmark = [pytest.mark.requires_jax, pytest.mark.requires_db, pytest.mark.integration]

DB_PATH = "ASD_da/libs_production.db"
_REPO_ROOT = Path(__file__).resolve().parents[2]
_REAL_SPECTRUM = _REPO_ROOT / "data" / "bhvo2_usgs" / "chemcam_bhvo2_loc1_spectrum.csv"

# Parity config: the shared solve math path (see module docstring).
_PARITY_OVERRIDES = {
    "closure_mode": "standard",
    "saha_boltzmann_graph": False,
    "stark_ne": False,
    "response_curve": None,
}


@pytest.fixture(scope="module")
def db():
    from cflibs.atomic.database import AtomicDatabase

    if not Path(DB_PATH).exists():  # pragma: no cover - env-dependent
        pytest.skip(f"atomic DB not present at {DB_PATH}")
    return AtomicDatabase(DB_PATH)


@pytest.fixture(scope="module")
def snapshot():
    from cflibs.jitpipe import build_snapshot

    if not Path(DB_PATH).exists():  # pragma: no cover
        pytest.skip(f"atomic DB not present at {DB_PATH}")
    return build_snapshot(DB_PATH)


def _static_for(snapshot, closure_mode="standard", max_iters=20):
    from cflibs.jitpipe import StaticConfig

    return StaticConfig(
        bucket_id=0,
        n_species=snapshot.n_species,
        level_pad=snapshot.level_pad[1],
        closure_mode=closure_mode,
        max_iters=max_iters,
    )


def _synthetic_spectrum(db, T_K=9000.0, n_e=2.0e16, lam=(240.0, 450.0), dlam=0.02):
    """Deterministic synthetic spectrum via the CF-LIBS forward model."""
    from cflibs.instrument.model import InstrumentModel
    from cflibs.plasma.state import SingleZoneLTEPlasma
    from cflibs.radiation.spectrum_model import SpectrumModel

    species = {"Fe": 5.0e15, "Ca": 3.0e15, "Ti": 2.0e15}
    plasma = SingleZoneLTEPlasma(T_e=T_K, n_e=n_e, species=species)
    instr = InstrumentModel(resolution_fwhm_nm=0.05)
    model = SpectrumModel(plasma, db, instr, lam[0], lam[1], dlam)
    wl, inten = model.compute_spectrum()
    return np.asarray(wl, float), np.asarray(inten, float), list(species.keys())


def _load_real_spectrum():
    rows = np.genfromtxt(_REAL_SPECTRUM, delimiter=",", names=True)
    return np.asarray(rows["wavelength"], float), np.asarray(rows["intensity"], float)


def _assert_m1_parity(ref, got, *, elements):
    """Assert the M1 tolerances between a reference and jit CFLIBSResult."""
    # 1. Element calls agree (every present element must match here).
    ref_calls = {k for k, v in ref.concentrations.items() if v > 0.0}
    got_calls = {k for k, v in got.concentrations.items() if v > 0.0}
    assert got_calls == ref_calls, f"element calls differ: jit={got_calls} ref={ref_calls}"

    # 2. T within 2 %, n_e within 10 %.
    np.testing.assert_allclose(got.temperature_K, ref.temperature_K, rtol=0.02)
    np.testing.assert_allclose(got.electron_density_cm3, ref.electron_density_cm3, rtol=0.10)

    # 3. Per-element concentration rtol 5 % / atol 0.01.
    for el in ref.concentrations:
        np.testing.assert_allclose(
            got.concentrations.get(el, 0.0),
            ref.concentrations[el],
            rtol=0.05,
            atol=0.01,
            err_msg=f"concentration parity failed for {el}",
        )


# ---------------------------------------------------------------------------
# 1. Synthetic end-to-end composition parity (no external data).
# ---------------------------------------------------------------------------


def test_run_one_matches_reference_synthetic(db, snapshot):
    """run_one reproduces run_pipeline end-to-end on a synthetic spectrum.

    Exercises the full COMPOSITION: response/preprocess -> calibrate -> detect
    + identify -> solve. The solve spine runs the jit ``scan_solve`` kernel; the
    reference runs its own solve on the same observations. M1 tolerances.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
    )
    _assert_m1_parity(ref, got, elements=elements)


def test_run_one_returns_cflibs_result_type(db, snapshot):
    """run_one returns the SAME ``CFLIBSResult`` dataclass the reference returns."""
    from cflibs.inversion.pipeline import build_pipeline_config
    from cflibs.inversion.solve.iterative import CFLIBSResult
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)
    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
    )
    assert isinstance(got, CFLIBSResult)
    assert set(got.concentrations) == set(elements)


# ---------------------------------------------------------------------------
# 2. Real ChemCam BHVO-2 end-to-end parity (when the fixture is present).
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not _REAL_SPECTRUM.exists(), reason="real ChemCam BHVO-2 fixture not present in worktree"
)
def test_run_one_matches_reference_real_chemcam(db, snapshot):
    """run_one reproduces run_pipeline on a REAL ChemCam BHVO-2 spectrum (M1 headline)."""
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten = _load_real_spectrum()
    elements = ["Si", "Ti", "Al", "Fe", "Mn", "Mg", "Ca", "Na", "K"]
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)

    ref, diag = run_pipeline(wl, inten, db, cfg)
    assert diag["n_observations"] > 0

    got = run_one(
        inten,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
    )
    _assert_m1_parity(ref, got, elements=elements)


# ---------------------------------------------------------------------------
# 3. Failure-policy parity (AC4): zero usable lines -> same all-FN record.
# ---------------------------------------------------------------------------


def test_failure_policy_parity(db, snapshot):
    """A flat (peak-free) spectrum: reference raises ValueError, jit returns all-FN.

    The reference scoreboard scores the ValueError as all false-negative; the
    jit pipeline must emit the same all-FN record (NaN-free, ``converged=False``,
    element keys preserved) — not a crash, not NaN.
    """
    from cflibs.inversion.pipeline import build_pipeline_config, run_pipeline
    from cflibs.jitpipe import PipelineParams, run_one

    wl = np.arange(240.0, 450.0, 0.02)
    flat = np.ones_like(wl)
    elements = ["Fe", "Ca", "Ti"]
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)

    # Reference: zero observations -> ValueError.
    with pytest.raises(ValueError, match="No usable spectral lines"):
        run_pipeline(wl, flat, db, cfg)

    # Jit: same all-FN record (no crash, no NaN).
    got = run_one(
        flat,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_config=cfg,
    )
    assert got.converged is False
    assert set(got.concentrations) == set(elements)
    assert all(v == 0.0 for v in got.concentrations.values())
    assert np.isfinite(got.temperature_K)
    assert np.isfinite(got.electron_density_cm3)
    assert not any(np.isnan(v) for v in got.concentrations.values())


# ---------------------------------------------------------------------------
# 4. run_batch host-loop produces per-spectrum CFLIBSResults.
# ---------------------------------------------------------------------------


def test_run_batch_host_loop(db, snapshot):
    """run_batch returns one CFLIBSResult per spectrum (J8 host loop; vmap in J9)."""
    from cflibs.inversion.pipeline import build_pipeline_config
    from cflibs.inversion.solve.iterative import CFLIBSResult
    from cflibs.jitpipe import PipelineParams, run_batch

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)
    batch = np.stack([inten, inten * 1.001])  # two near-identical spectra
    results = run_batch(
        batch,
        wl,
        snapshot,
        PipelineParams(),
        _static_for(snapshot),
        atomic_db=db,
        pipeline_configs=[cfg, cfg],
    )
    assert len(results) == 2
    assert all(isinstance(r, CFLIBSResult) for r in results)
    assert all(set(r.concentrations) == set(elements) for r in results)


# ---------------------------------------------------------------------------
# 5. solve-stage padding invariance at the composition level (AC5/AC6 surface).
# ---------------------------------------------------------------------------


def test_solve_stage_bucket_invariance(db, snapshot):
    """A larger static max_iters bucket leaves the answer unchanged (idempotent freeze)."""
    from cflibs.inversion.pipeline import build_pipeline_config
    from cflibs.jitpipe import PipelineParams, run_one

    wl, inten, elements = _synthetic_spectrum(db)
    cfg = build_pipeline_config(elements, preset="raw", overrides=_PARITY_OVERRIDES)
    params = PipelineParams()

    r20 = run_one(
        inten,
        wl,
        snapshot,
        params,
        _static_for(snapshot, max_iters=20),
        atomic_db=db,
        pipeline_config=cfg,
    )
    r30 = run_one(
        inten,
        wl,
        snapshot,
        params,
        _static_for(snapshot, max_iters=30),
        atomic_db=db,
        pipeline_config=cfg,
    )
    # The converged-state freeze makes scan_solve idempotent past convergence.
    np.testing.assert_allclose(r30.temperature_K, r20.temperature_K, rtol=1e-9)
    for el in elements:
        np.testing.assert_allclose(
            r30.concentrations[el], r20.concentrations[el], rtol=1e-9, atol=1e-12
        )
