"""Real-data confirmation report data."""
# fmt: off
_META = {"version": "v1.0", "datasets_tested": ["AA1100_substrate", "Ti6Al4V_substrate", "20shot"], "datasets_unavailable": ["steel_245nm", "Fe_245nm", "Ni_245nm", "FeNi_380nm", "FeNi_480nm", "FeNi_single"]}
_COND = {"wavelength_calibration": "none (also tested with auto)", "resolving_power": {"AA1100_substrate": 500, "Ti6Al4V_substrate": 500, "20shot": 842}}
_AA = {"expected": ["Al"], "wavelength_range_nm": "279.86-320.04", "ALIAS": {"detected": ["Al", "Co", "Fe", "Ni", "Si", "Ti"], "missed_expected": [], "false_positives": ["Co", "Fe", "Ni", "Si", "Ti"], "al_score": 0.816, "al_confidence": 0.195}, "Comb": {"detected": ["Mg", "Si", "V"], "missed_expected": ["Al"], "false_positives": ["Mg", "Si", "V"]}, "Correlation": {"detected": ["Cu", "Mn", "Si", "V"], "missed_expected": ["Al"], "false_positives": ["Cu", "Mn", "Si", "V"]}}
_TI = {"expected": ["Ti", "Al", "V"], "wavelength_range_nm": "279.03-320.86", "ALIAS": {"detected": ["Al", "Cu", "Fe", "Mn", "Ni", "Ti", "V"], "missed_expected": [], "true_positives": ["Al", "Ti", "V"], "false_positives": ["Cu", "Fe", "Mn", "Ni"], "al_score": 0.701, "ti_score": 0.688, "v_score": 0.433}, "Comb": {"detected": ["Cu", "Mg", "Si"], "missed_expected": ["Ti", "Al", "V"], "false_positives": ["Cu", "Mg", "Si"]}, "Correlation": {"detected": ["Cr", "Cu"], "missed_expected": ["Ti", "Al", "V"], "false_positives": ["Cr", "Cu"]}}
_SHOT = {"expected": ["Fe", "Ti", "Ni"], "wavelength_range_nm": "286.39-326.51", "ALIAS": {"detected": ["Ti"], "missed_expected": ["Fe", "Ni"], "true_positives": ["Ti"], "false_positives": [], "ti_score": 0.555}, "Comb": {"detected": [], "missed_expected": ["Fe", "Ti", "Ni"], "false_positives": []}, "Correlation": {"detected": [], "missed_expected": ["Fe", "Ti", "Ni"], "false_positives": []}}
_BENCH = {"ALIAS": {"TP": 5, "FP": 9, "FN": 2, "TN": 11, "precision": 0.357, "recall": 0.714, "fpr": 0.45, "recall_pass": True, "fpr_pass": False, "verdict": "FAIL (high FPR)"}, "Comb": {"TP": 0, "FP": 3, "FN": 7, "TN": 17, "precision": 0.0, "recall": 0.0, "fpr": 0.15, "recall_pass": False, "fpr_pass": True, "verdict": "FAIL (no recall)"}, "Correlation": {"TP": 0, "FP": 4, "FN": 7, "TN": 16, "precision": 0.0, "recall": 0.0, "fpr": 0.2, "recall_pass": False, "fpr_pass": True, "verdict": "FAIL (no recall)"}}
_CAL = {"mode_tested": "auto (shift model)", "ALIAS": "Same recall (71.4%), worse FPR (45% to 55%) due to more FP triggers after shift correction", "Comb": "No improvement; 0% recall with or without calibration", "Correlation": "Worse; FPR increased from 20% to 35% with calibration"}
_FAIL = {"ALIAS_high_FPR": "At RP=500 broad lines overlap causing false matches for Co Fe Ni Si Ti on AA1100 pure Al", "Comb_zero_recall": "Comb template matching requires clean isolated peaks; at RP=500 most teeth blend into broad features", "Correlation_zero_recall": "Correlation identifier struggles at low RP because synthetic templates at higher resolution do not match blended real-data line shapes", "20shot_low_detection": "Only Ti detected by ALIAS. Fe and Ni lines in 286-326nm range are weaker than Ti II features at LIBS plasma temperatures"}
_RECS = {"ALIAS": "Best performer at low RP. Consider element-specific confidence thresholds to reduce FPs for Co Ni Fe which are common false positives at RP~500.", "Comb": "Not suitable for low-RP broadband spectrometers. Restrict to echelle data with RP>3000.", "Correlation": "Needs RP-matched synthetic templates. Generate RP=500 templates for broadband use.", "general": "Acquire NetCDF datasets with RP>3000 echelle data for full benchmark coverage.", "next_steps": ["Implement element-specific detection thresholds for ALIAS", "Generate low-RP synthetic templates for Correlation identifier", "Add Comb RP guard to skip Comb when RP < 2000", "Acquire high-RP real data for complete benchmark"]}
_VERDICT = "BENCHMARK FAILED. ALIAS shows promising recall (71%) but high FPR (45%) at low resolving power. Comb and Correlation are ineffective at RP=500. Results are consistent with synthetic benchmark findings where ALIAS was the strongest identifier."
REPORT = {**_META, "test_conditions": _COND, "per_dataset_results": {"AA1100_substrate": _AA, "Ti6Al4V_substrate": _TI, "20shot": _SHOT}, "benchmark_summary": _BENCH, "calibration_effect": _CAL, "failure_mode_analysis": _FAIL, "recommendations": _RECS, "overall_verdict": _VERDICT}
