#!/usr/bin/env python3
"""Validate Kramida 2024 NIST Aki uncertainty refresh (PR #71 follow-up).

Queries the atomic DB before and after the refresh, computes median
sigma(A_ki) per species for Fe I, Fe II, Cr II, Mn II, and emits a
markdown delta table to docs/atomic_data/kramida_2024_delta.md.

Run from a fresh clone:

    python scripts/validate_kramida_2024.py \\
        --before path/to/atomic_pre_kramida2024.sqlite \\
        --after  path/to/atomic_post_kramida2024.sqlite \\
        --out    docs/atomic_data/kramida_2024_delta.md

If --before / --after are omitted, the script falls back to the
canonical paths under /cluster/shared/cf-libs-data/nist/ as documented
in the repo notes. Output is deterministic: rows are emitted in the
fixed species order [Fe I, Fe II, Cr II, Mn II] and numeric values are
formatted with fixed precision.
"""
from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path
from statistics import median

SPECIES = [
    ("Fe", 1, "Fe I"),
    ("Fe", 2, "Fe II"),
    ("Cr", 2, "Cr II"),
    ("Mn", 2, "Mn II"),
]

DEFAULT_BEFORE = Path(
    "/cluster/shared/cf-libs-data/nist/atomic_pre_kramida2024.sqlite"
)
DEFAULT_AFTER = Path(
    "/cluster/shared/cf-libs-data/nist/atomic_post_kramida2024.sqlite"
)


def median_sigma_aki(db: Path, element: str, ion_stage: int) -> float | None:
    """Return median sigma(A_ki) for the given species, or None if empty.

    Schema assumption (matches cflibs/atomic adapters): a `lines` table
    with columns (element TEXT, ion_stage INTEGER, aki REAL,
    aki_uncertainty REAL). Rows with NULL or non-positive uncertainty
    are excluded so that "Aki accuracy code only" rows don't bias the
    median downward.
    """
    conn = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    try:
        cur = conn.execute(
            """
            SELECT aki_uncertainty
            FROM lines
            WHERE element = ?
              AND ion_stage = ?
              AND aki_uncertainty IS NOT NULL
              AND aki_uncertainty > 0
            """,
            (element, ion_stage),
        )
        vals = [row[0] for row in cur.fetchall()]
    finally:
        conn.close()
    if not vals:
        return None
    return float(median(vals))


def fmt(v: float | None) -> str:
    return "n/a" if v is None else f"{v:.4f}"


def fmt_delta(before: float | None, after: float | None) -> tuple[str, str]:
    if before is None or after is None or before == 0:
        return ("n/a", "n/a")
    abs_delta = after - before
    rel_delta = 100.0 * abs_delta / before
    return (f"{abs_delta:+.4f}", f"{rel_delta:+.1f}%")


def build_table(before_db: Path, after_db: Path) -> tuple[str, int]:
    rows = []
    improved = 0
    for element, ion_stage, label in SPECIES:
        b = median_sigma_aki(before_db, element, ion_stage)
        a = median_sigma_aki(after_db, element, ion_stage)
        abs_d, rel_d = fmt_delta(b, a)
        if b is not None and a is not None and a < b:
            improved += 1
        rows.append((label, fmt(b), fmt(a), abs_d, rel_d))

    header = (
        "| Species | Median sigma(A_ki) before | Median sigma(A_ki) after | "
        "Absolute delta | Relative delta |\n"
        "|---|---|---|---|---|\n"
    )
    body = "\n".join(
        f"| {label} | {b} | {a} | {ad} | {rd} |"
        for label, b, a, ad, rd in rows
    )
    return header + body + "\n", improved


def render_markdown(before_db: Path, after_db: Path) -> tuple[str, int]:
    table, improved = build_table(before_db, after_db)
    doc = (
        "# Kramida 2024 NIST Aki uncertainty refresh — delta report\n\n"
        "Generated by `scripts/validate_kramida_2024.py` as a "
        "follow-up to PR #71.\n\n"
        f"- Before DB: `{before_db}`\n"
        f"- After DB:  `{after_db}`\n\n"
        "## Median sigma(A_ki) per species\n\n"
        + table
        + "\n"
        "Median is computed over rows with strictly positive "
        "`aki_uncertainty`; rows carrying only an accuracy code are "
        "excluded.\n"
    )
    return doc, improved


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--before", type=Path, default=DEFAULT_BEFORE)
    parser.add_argument("--after", type=Path, default=DEFAULT_AFTER)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("docs/atomic_data/kramida_2024_delta.md"),
    )
    parser.add_argument(
        "--min-improved",
        type=int,
        default=3,
        help="Minimum number of species that must show a reduction.",
    )
    args = parser.parse_args(argv)

    for db in (args.before, args.after):
        if not db.exists():
            print(f"error: atomic DB not found: {db}", file=sys.stderr)
            return 2

    doc, improved = render_markdown(args.before, args.after)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(doc, encoding="utf-8")
    print(f"wrote {args.out} ({improved}/{len(SPECIES)} species improved)")

    if improved < args.min_improved:
        print(
            f"error: only {improved} species showed reduced median "
            f"sigma(A_ki); expected >= {args.min_improved}",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
